DROP TABLE IF EXISTS `country_info`;

CREATE TABLE IF NOT EXISTS `country_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `iso_code_2` varchar(2) NOT NULL COMMENT 'ISO 3166-1 二字母代码',
  `iso_code_3` varchar(3) NOT NULL COMMENT 'ISO 3166-1 三字母代码',
  `iso_code_numeric` varchar(3) NOT NULL COMMENT 'ISO 3166-1 数字代码',
  `name_en` varchar(100) NOT NULL COMMENT '国家/地区英文名称',
  `name_zh` varchar(100) NOT NULL COMMENT '国家/地区中文名称',
  `sovereignty` varchar(50) DEFAULT NULL COMMENT '主权状态',
  `continent` varchar(20) NOT NULL COMMENT '所属大洲',
  `currency_code` varchar(3) DEFAULT NULL COMMENT 'ISO 4217 货币代码',
  `phone_code` varchar(10) DEFAULT NULL COMMENT '国际电话区号',
  `timezone_iana` varchar(50) DEFAULT NULL COMMENT '主要 IANA 时区',
  PRIMARY KEY (`id`),
  UNIQUE KEY `iso_code_2` (`iso_code_2`),
  UNIQUE KEY `iso_code_3` (`iso_code_3`)
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC COMMENT = '全球国家和地区信息';


INSERT INTO `country_info` (`iso_code_2`, `iso_code_3`, `iso_code_numeric`, `name_en`, `name_zh`, `sovereignty`, `continent`, `currency_code`, `phone_code`, `timezone_iana`) VALUES
('AF', 'AFG', '004', 'Afghanistan', '阿富汗', 'Sovereign state', 'Asia', 'AFN', '93', 'Asia/Kabul'),
('AL', 'ALB', '008', 'Albania', '阿尔巴尼亚', 'Sovereign state', 'Europe', 'ALL', '355', 'Europe/Tirane'),
('DZ', 'DZA', '012', 'Algeria', '阿尔及利亚', 'Sovereign state', 'Africa', 'DZD', '213', 'Africa/Algiers'),
('AS', 'ASM', '016', 'American Samoa', '美属萨摩亚', 'US territory', 'Oceania', 'USD', '1-684', 'Pacific/Pago_Pago'),
('AD', 'AND', '020', 'Andorra', '安道尔', 'Sovereign state', 'Europe', 'EUR', '376', 'Europe/Andorra'),
('AO', 'AGO', '024', 'Angola', '安哥拉', 'Sovereign state', 'Africa', 'AOA', '244', 'Africa/Luanda'),
('AI', 'AIA', '660', 'Anguilla', '安圭拉', 'UK territory', 'North America', 'XCD', '1-264', 'America/Anguilla'),
('AQ', 'ATA', '010', 'Antarctica', '南极洲', 'No recognized sovereign state', 'Antarctica', NULL, NULL, 'Antarctica/Casey'),
('AG', 'ATG', '028', 'Antigua and Barbuda', '安提瓜和巴布达', 'Sovereign state', 'North America', 'XCD', '1-268', 'America/Antigua'),
('AR', 'ARG', '032', 'Argentina', '阿根廷', 'Sovereign state', 'South America', 'ARS', '54', 'America/Argentina/Buenos_Aires'),
('AM', 'ARM', '051', 'Armenia', '亚美尼亚', 'Sovereign state', 'Asia', 'AMD', '374', 'Asia/Yerevan'),
('AW', 'ABW', '533', 'Aruba', '阿鲁巴', 'Netherlands territory', 'North America', 'AWG', '297', 'America/Aruba'),
('AU', 'AUS', '036', 'Australia', '澳大利亚', 'Sovereign state', 'Oceania', 'AUD', '61', 'Australia/Sydney'),
('AT', 'AUT', '040', 'Austria', '奥地利', 'Sovereign state', 'Europe', 'EUR', '43', 'Europe/Vienna'),
('AZ', 'AZE', '031', 'Azerbaijan', '阿塞拜疆', 'Sovereign state', 'Asia', 'AZN', '994', 'Asia/Baku'),
('BS', 'BHS', '044', 'Bahamas', '巴哈马', 'Sovereign state', 'North America', 'BSD', '1-242', 'America/Nassau'),
('BH', 'BHR', '048', 'Bahrain', '巴林', 'Sovereign state', 'Asia', 'BHD', '973', 'Asia/Bahrain'),
('BD', 'BGD', '050', 'Bangladesh', '孟加拉国', 'Sovereign state', 'Asia', 'BDT', '880', 'Asia/Dhaka'),
('BB', 'BRB', '052', 'Barbados', '巴巴多斯', 'Sovereign state', 'North America', 'BBD', '1-246', 'America/Barbados'),
('BY', 'BLR', '112', 'Belarus', '白俄罗斯', 'Sovereign state', 'Europe', 'BYN', '375', 'Europe/Minsk'),
('BE', 'BEL', '056', 'Belgium', '比利时', 'Sovereign state', 'Europe', 'EUR', '32', 'Europe/Brussels'),
('BZ', 'BLZ', '084', 'Belize', '伯利兹', 'Sovereign state', 'North America', 'BZD', '501', 'America/Belize'),
('BJ', 'BEN', '204', 'Benin', '贝宁', 'Sovereign state', 'Africa', 'XOF', '229', 'Africa/Porto-Novo'),
('BM', 'BMU', '060', 'Bermuda', '百慕大', 'UK territory', 'North America', 'BMD', '1-441', 'Atlantic/Bermuda'),
('BT', 'BTN', '064', 'Bhutan', '不丹', 'Sovereign state', 'Asia', 'BTN', '975', 'Asia/Thimphu'),
('BO', 'BOL', '068', 'Bolivia', '玻利维亚', 'Sovereign state', 'South America', 'BOB', '591', 'America/La_Paz'),
('BA', 'BIH', '070', 'Bosnia and Herzegovina', '波斯尼亚和黑塞哥维那', 'Sovereign state', 'Europe', 'BAM', '387', 'Europe/Sarajevo'),
('BW', 'BWA', '072', 'Botswana', '博茨瓦纳', 'Sovereign state', 'Africa', 'BWP', '267', 'Africa/Gaborone'),
('BR', 'BRA', '076', 'Brazil', '巴西', 'Sovereign state', 'South America', 'BRL', '55', 'America/Sao_Paulo'),
('IO', 'IOT', '086', 'British Indian Ocean Territory', '英属印度洋领地', 'UK territory', 'Asia', 'USD', '246', 'Indian/Chagos'),
('VG', 'VGB', '092', 'British Virgin Islands', '英属维尔京群岛', 'UK territory', 'North America', 'USD', '1-284', 'America/Tortola'),
('BN', 'BRN', '096', 'Brunei Darussalam', '文莱', 'Sovereign state', 'Asia', 'BND', '673', 'Asia/Brunei'),
('BG', 'BGR', '100', 'Bulgaria', '保加利亚', 'Sovereign state', 'Europe', 'BGN', '359', 'Europe/Sofia'),
('BF', 'BFA', '854', 'Burkina Faso', '布基纳法索', 'Sovereign state', 'Africa', 'XOF', '226', 'Africa/Ouagadougou'),
('BI', 'BDI', '108', 'Burundi', '布隆迪', 'Sovereign state', 'Africa', 'BIF', '257', 'Africa/Bujumbura'),
('KH', 'KHM', '116', 'Cambodia', '柬埔寨', 'Sovereign state', 'Asia', 'KHR', '855', 'Asia/Phnom_Penh'),
('CM', 'CMR', '120', 'Cameroon', '喀麦隆', 'Sovereign state', 'Africa', 'XAF', '237', 'Africa/Douala'),
('CA', 'CAN', '124', 'Canada', '加拿大', 'Sovereign state', 'North America', 'CAD', '1', 'America/Toronto'),
('CV', 'CPV', '132', 'Cabo Verde', '佛得角', 'Sovereign state', 'Africa', 'CVE', '238', 'Atlantic/Cape_Verde'),
('KY', 'CYM', '136', 'Cayman Islands', '开曼群岛', 'UK territory', 'North America', 'KYD', '1-345', 'America/Cayman'),
('CF', 'CAF', '140', 'Central African Republic', '中非', 'Sovereign state', 'Africa', 'XAF', '236', 'Africa/Bangui'),
('TD', 'TCD', '148', 'Chad', '乍得', 'Sovereign state', 'Africa', 'XAF', '235', 'Africa/Ndjamena'),
('CL', 'CHL', '152', 'Chile', '智利', 'Sovereign state', 'South America', 'CLP', '56', 'America/Santiago'),
('CN', 'CHN', '156', 'China', '中国', 'Sovereign state', 'Asia', 'CNY', '86', 'Asia/Shanghai'),
('CX', 'CXR', '162', 'Christmas Island', '圣诞岛', 'Australian territory', 'Asia', 'AUD', '61', 'Indian/Christmas'),
('CC', 'CCK', '166', 'Cocos (Keeling) Islands', '科科斯（基林）群岛', 'Australian territory', 'Asia', 'AUD', '61', 'Indian/Cocos'),
('CO', 'COL', '170', 'Colombia', '哥伦比亚', 'Sovereign state', 'South America', 'COP', '57', 'America/Bogota'),
('KM', 'COM', '174', 'Comoros', '科摩罗', 'Sovereign state', 'Africa', 'KMF', '269', 'Indian/Comoro'),
('CK', 'COK', '184', 'Cook Islands', '库克群岛', 'New Zealand territory', 'Oceania', 'NZD', '682', 'Pacific/Rarotonga'),
('CR', 'CRI', '188', 'Costa Rica', '哥斯达黎加', 'Sovereign state', 'North America', 'CRC', '506', 'America/Costa_Rica'),
('HR', 'HRV', '191', 'Croatia', '克罗地亚', 'Sovereign state', 'Europe', 'HRK', '385', 'Europe/Zagreb'),
('CU', 'CUB', '192', 'Cuba', '古巴', 'Sovereign state', 'North America', 'CUP', '53', 'America/Havana'),
('CW', 'CUW', '531', 'Curaçao', '库拉索', 'Netherlands territory', 'North America', 'ANG', '599', 'America/Curacao'),
('CY', 'CYP', '196', 'Cyprus', '塞浦路斯', 'Sovereign state', 'Asia', 'EUR', '357', 'Asia/Nicosia'),
('CZ', 'CZE', '203', 'Czechia', '捷克', 'Sovereign state', 'Europe', 'CZK', '420', 'Europe/Prague'),
('CI', 'CIV', '384', 'Côte d''Ivoire', '科特迪瓦', 'Sovereign state', 'Africa', 'XOF', '225', 'Africa/Abidjan'),
('CD', 'COD', '180', 'Democratic Republic of the Congo', '刚果（金）', 'Sovereign state', 'Africa', 'CDF', '243', 'Africa/Kinshasa'),
('DK', 'DNK', '208', 'Denmark', '丹麦', 'Sovereign state', 'Europe', 'DKK', '45', 'Europe/Copenhagen'),
('DJ', 'DJI', '262', 'Djibouti', '吉布提', 'Sovereign state', 'Africa', 'DJF', '253', 'Africa/Djibouti'),
('DM', 'DMA', '212', 'Dominica', '多米尼克', 'Sovereign state', 'North America', 'XCD', '1-767', 'America/Dominica'),
('DO', 'DOM', '214', 'Dominican Republic', '多米尼加', 'Sovereign state', 'North America', 'DOP', '1-809', 'America/Santo_Domingo'),
('EC', 'ECU', '218', 'Ecuador', '厄瓜多尔', 'Sovereign state', 'South America', 'USD', '593', 'America/Guayaquil'),
('EG', 'EGY', '818', 'Egypt', '埃及', 'Sovereign state', 'Africa', 'EGP', '20', 'Africa/Cairo'),
('SV', 'SLV', '222', 'El Salvador', '萨尔瓦多', 'Sovereign state', 'North America', 'USD', '503', 'America/El_Salvador'),
('GQ', 'GNQ', '226', 'Equatorial Guinea', '赤道几内亚', 'Sovereign state', 'Africa', 'XAF', '240', 'Africa/Malabo'),
('ER', 'ERI', '232', 'Eritrea', '厄立特里亚', 'Sovereign state', 'Africa', 'ERN', '291', 'Africa/Asmara'),
('EE', 'EST', '233', 'Estonia', '爱沙尼亚', 'Sovereign state', 'Europe', 'EUR', '372', 'Europe/Tallinn'),
('SZ', 'SWZ', '748', 'Eswatini', '斯威士兰', 'Sovereign state', 'Africa', 'SZL', '268', 'Africa/Mbabane'),
('ET', 'ETH', '231', 'Ethiopia', '埃塞俄比亚', 'Sovereign state', 'Africa', 'ETB', '251', 'Africa/Addis_Ababa'),
('FK', 'FLK', '238', 'Falkland Islands (Malvinas)', '福克兰群岛（马尔维纳斯）', 'UK territory', 'South America', 'FKP', '500', 'Atlantic/Stanley'),
('FO', 'FRO', '234', 'Faroe Islands', '法罗群岛', 'Denmark territory', 'Europe', 'DKK', '298', 'Atlantic/Faroe'),
('FJ', 'FJI', '242', 'Fiji', '斐济', 'Sovereign state', 'Oceania', 'FJD', '679', 'Pacific/Fiji'),
('FI', 'FIN', '246', 'Finland', '芬兰', 'Sovereign state', 'Europe', 'EUR', '358', 'Europe/Helsinki'),
('FR', 'FRA', '250', 'France', '法国', 'Sovereign state', 'Europe', 'EUR', '33', 'Europe/Paris'),
('GF', 'GUF', '254', 'French Guiana', '法属圭亚那', 'France territory', 'South America', 'EUR', '594', 'America/Cayenne'),
('PF', 'PYF', '258', 'French Polynesia', '法属波利尼西亚', 'France territory', 'Oceania', 'XPF', '689', 'Pacific/Tahiti'),
('TF', 'ATF', '260', 'French Southern Territories', '法属南部领地', 'France territory', 'Antarctica', 'EUR', NULL, 'Indian/Kerguelen'),
('GA', 'GAB', '266', 'Gabon', '加蓬', 'Sovereign state', 'Africa', 'XAF', '241', 'Africa/Libreville'),
('GM', 'GMB', '270', 'Gambia', '冈比亚', 'Sovereign state', 'Africa', 'GMD', '220', 'Africa/Banjul'),
('GE', 'GEO', '268', 'Georgia', '格鲁吉亚', 'Sovereign state', 'Asia', 'GEL', '995', 'Asia/Tbilisi'),
('DE', 'DEU', '276', 'Germany', '德国', 'Sovereign state', 'Europe', 'EUR', '49', 'Europe/Berlin'),
('GH', 'GHA', '288', 'Ghana', '加纳', 'Sovereign state', 'Africa', 'GHS', '233', 'Africa/Accra'),
('GI', 'GIB', '292', 'Gibraltar', '直布罗陀', 'UK territory', 'Europe', 'GIP', '350', 'Europe/Gibraltar'),
('GR', 'GRC', '300', 'Greece', '希腊', 'Sovereign state', 'Europe', 'EUR', '30', 'Europe/Athens'),
('GL', 'GRL', '304', 'Greenland', '格陵兰', 'Denmark territory', 'North America', 'DKK', '299', 'America/Godthab'),
('GD', 'GRD', '308', 'Grenada', '格林纳达', 'Sovereign state', 'North America', 'XCD', '1-473', 'America/Grenada'),
('GP', 'GLP', '312', 'Guadeloupe', '瓜德罗普', 'France territory', 'North America', 'EUR', '590', 'America/Guadeloupe'),
('GU', 'GUM', '316', 'Guam', '关岛', 'US territory', 'Oceania', 'USD', '1-671', 'Pacific/Guam'),
('GT', 'GTM', '320', 'Guatemala', '危地马拉', 'Sovereign state', 'North America', 'GTQ', '502', 'America/Guatemala'),
('GG', 'GGY', '831', 'Guernsey', '根西', 'UK territory', 'Europe', 'GBP', '44', 'Europe/Guernsey'),
('GN', 'GIN', '324', 'Guinea', '几内亚', 'Sovereign state', 'Africa', 'GNF', '224', 'Africa/Conakry'),
('GW', 'GNB', '624', 'Guinea-Bissau', '几内亚比绍', 'Sovereign state', 'Africa', 'XOF', '245', 'Africa/Bissau'),
('GY', 'GUY', '328', 'Guyana', '圭亚那', 'Sovereign state', 'South America', 'GYD', '592', 'America/Guyana'),
('HT', 'HTI', '332', 'Haiti', '海地', 'Sovereign state', 'North America', 'HTG', '509', 'America/Port-au-Prince'),
('HM', 'HMD', '334', 'Heard Island and McDonald Islands', '赫德岛和麦克唐纳群岛', 'Australian territory', 'Antarctica', 'AUD', '61', 'Antarctica/Casey'),
('VA', 'VAT', '336', 'Holy See', '梵蒂冈', 'Sovereign state', 'Europe', 'EUR', '379', 'Europe/Vatican'),
('HN', 'HND', '340', 'Honduras', '洪都拉斯', 'Sovereign state', 'North America', 'HNL', '504', 'America/Tegucigalpa'),
('HK', 'HKG', '344', 'Hong Kong', '中国香港特别行政区', 'Chinese special administrative region', 'Asia', 'HKD', '852', 'Asia/Hong_Kong'),
('HU', 'HUN', '348', 'Hungary', '匈牙利', 'Sovereign state', 'Europe', 'HUF', '36', 'Europe/Budapest'),
('IS', 'ISL', '352', 'Iceland', '冰岛', 'Sovereign state', 'Europe', 'ISK', '354', 'Atlantic/Reykjavik'),
('IN', 'IND', '356', 'India', '印度', 'Sovereign state', 'Asia', 'INR', '91', 'Asia/Kolkata'),
('ID', 'IDN', '360', 'Indonesia', '印度尼西亚', 'Sovereign state', 'Asia', 'IDR', '62', 'Asia/Jakarta'),
('IR', 'IRN', '364', 'Iran', '伊朗', 'Sovereign state', 'Asia', 'IRR', '98', 'Asia/Tehran'),
('IQ', 'IRQ', '368', 'Iraq', '伊拉克', 'Sovereign state', 'Asia', 'IQD', '964', 'Asia/Baghdad'),
('IE', 'IRL', '372', 'Ireland', '爱尔兰', 'Sovereign state', 'Europe', 'EUR', '353', 'Europe/Dublin'),
('IM', 'IMN', '833', 'Isle of Man', '马恩岛', 'UK territory', 'Europe', 'GBP', '44', 'Europe/Isle_of_Man'),
('IL', 'ISR', '376', 'Israel', '以色列', 'Sovereign state', 'Asia', 'ILS', '972', 'Asia/Jerusalem'),
('IT', 'ITA', '380', 'Italy', '意大利', 'Sovereign state', 'Europe', 'EUR', '39', 'Europe/Rome'),
('JM', 'JAM', '388', 'Jamaica', '牙买加', 'Sovereign state', 'North America', 'JMD', '1-876', 'America/Jamaica'),
('JP', 'JPN', '392', 'Japan', '日本', 'Sovereign state', 'Asia', 'JPY', '81', 'Asia/Tokyo'),
('JE', 'JEY', '832', 'Jersey', '泽西岛', 'UK territory', 'Europe', 'GBP', '44', 'Europe/Jersey'),
('JO', 'JOR', '400', 'Jordan', '约旦', 'Sovereign state', 'Asia', 'JOD', '962', 'Asia/Amman'),
('KZ', 'KAZ', '398', 'Kazakhstan', '哈萨克斯坦', 'Sovereign state', 'Asia', 'KZT', '7', 'Asia/Almaty'),
('KE', 'KEN', '404', 'Kenya', '肯尼亚', 'Sovereign state', 'Africa', 'KES', '254', 'Africa/Nairobi'),
('KI', 'KIR', '296', 'Kiribati', '基里巴斯', 'Sovereign state', 'Oceania', 'AUD', '686', 'Pacific/Tarawa'),
('KP', 'PRK', '408', 'North Korea', '朝鲜', 'Sovereign state', 'Asia', 'KPW', '850', 'Asia/Pyongyang'),
('KR', 'KOR', '410', 'South Korea', '韩国', 'Sovereign state', 'Asia', 'KRW', '82', 'Asia/Seoul'),
('KW', 'KWT', '414', 'Kuwait', '科威特', 'Sovereign state', 'Asia', 'KWD', '965', 'Asia/Kuwait'),
('KG', 'KGZ', '417', 'Kyrgyzstan', '吉尔吉斯斯坦', 'Sovereign state', 'Asia', 'KGS', '996', 'Asia/Bishkek'),
('LA', 'LAO', '418', 'Laos', '老挝', 'Sovereign state', 'Asia', 'LAK', '856', 'Asia/Vientiane'),
('LV', 'LVA', '428', 'Latvia', '拉脱维亚', 'Sovereign state', 'Europe', 'EUR', '371', 'Europe/Riga'),
('LB', 'LBN', '422', 'Lebanon', '黎巴嫩', 'Sovereign state', 'Asia', 'LBP', '961', 'Asia/Beirut'),
('LS', 'LSO', '426', 'Lesotho', '莱索托', 'Sovereign state', 'Africa', 'LSL', '266', 'Africa/Maseru'),
('LR', 'LBR', '430', 'Liberia', '利比里亚', 'Sovereign state', 'Africa', 'LRD', '231', 'Africa/Monrovia'),
('LY', 'LBY', '434', 'Libya', '利比亚', 'Sovereign state', 'Africa', 'LYD', '218', 'Africa/Tripoli'),
('LI', 'LIE', '438', 'Liechtenstein', '列支敦士登', 'Sovereign state', 'Europe', 'CHF', '423', 'Europe/Vaduz'),
('LT', 'LTU', '440', 'Lithuania', '立陶宛', 'Sovereign state', 'Europe', 'EUR', '370', 'Europe/Vilnius'),
('LU', 'LUX', '442', 'Luxembourg', '卢森堡', 'Sovereign state', 'Europe', 'EUR', '352', 'Europe/Luxembourg'),
('MO', 'MAC', '446', 'Macao', '中国澳门特别行政区', 'Chinese special administrative region', 'Asia', 'MOP', '853', 'Asia/Macau'),
('MG', 'MDG', '450', 'Madagascar', '马达加斯加', 'Sovereign state', 'Africa', 'MGA', '261', 'Indian/Antananarivo'),
('MW', 'MWI', '454', 'Malawi', '马拉维', 'Sovereign state', 'Africa', 'MWK', '265', 'Africa/Blantyre'),
('MY', 'MYS', '458', 'Malaysia', '马来西亚', 'Sovereign state', 'Asia', 'MYR', '60', 'Asia/Kuala_Lumpur'),
('MV', 'MDV', '462', 'Maldives', '马尔代夫', 'Sovereign state', 'Asia', 'MVR', '960', 'Indian/Maldives'),
('ML', 'MLI', '466', 'Mali', '马里', 'Sovereign state', 'Africa', 'XOF', '223', 'Africa/Bamako'),
('MT', 'MLT', '470', 'Malta', '马耳他', 'Sovereign state', 'Europe', 'EUR', '356', 'Europe/Malta'),
('MH', 'MHL', '584', 'Marshall Islands', '马绍尔群岛', 'Sovereign state', 'Oceania', 'USD', '692', 'Pacific/Majuro'),
('MQ', 'MTQ', '474', 'Martinique', '马提尼克', 'France territory', 'North America', 'EUR', '596', 'America/Martinique'),
('MR', 'MRT', '478', 'Mauritania', '毛里塔尼亚', 'Sovereign state', 'Africa', 'MRU', '222', 'Africa/Nouakchott'),
('MU', 'MUS', '480', 'Mauritius', '毛里求斯', 'Sovereign state', 'Africa', 'MUR', '230', 'Indian/Mauritius'),
('MX', 'MEX', '484', 'Mexico', '墨西哥', 'Sovereign state', 'North America', 'MXN', '52', 'America/Mexico_City'),
('FM', 'FSM', '583', 'Micronesia', '密克罗尼西亚', 'Sovereign state', 'Oceania', 'USD', '691', 'Pacific/Pohnpei'),
('MD', 'MDA', '498', 'Moldova', '摩尔多瓦', 'Sovereign state', 'Europe', 'MDL', '373', 'Europe/Chisinau'),
('MC', 'MCO', '492', 'Monaco', '摩纳哥', 'Sovereign state', 'Europe', 'EUR', '377', 'Europe/Monaco'),
('MN', 'MNG', '496', 'Mongolia', '蒙古', 'Sovereign state', 'Asia', 'MNT', '976', 'Asia/Ulaanbaatar'),
('ME', 'MNE', '499', 'Montenegro', '黑山', 'Sovereign state', 'Europe', 'EUR', '382', 'Europe/Podgorica'),
('MS', 'MSR', '500', 'Montserrat', '蒙特塞拉特', 'UK territory', 'North America', 'XCD', '1-664', 'America/Montserrat'),
('MA', 'MAR', '504', 'Morocco', '摩洛哥', 'Sovereign state', 'Africa', 'MAD', '212', 'Africa/Casablanca'),
('MZ', 'MOZ', '508', 'Mozambique', '莫桑比克', 'Sovereign state', 'Africa', 'MZN', '258', 'Africa/Maputo'),
('MM', 'MMR', '104', 'Myanmar', '缅甸', 'Sovereign state', 'Asia', 'MMK', '95', 'Asia/Yangon'),
('NA', 'NAM', '516', 'Namibia', '纳米比亚', 'Sovereign state', 'Africa', 'NAD', '264', 'Africa/Windhoek'),
('NR', 'NRU', '520', 'Nauru', '瑙鲁', 'Sovereign state', 'Oceania', 'AUD', '674', 'Pacific/Nauru'),
('NP', 'NPL', '524', 'Nepal', '尼泊尔', 'Sovereign state', 'Asia', 'NPR', '977', 'Asia/Kathmandu'),
('NL', 'NLD', '528', 'Netherlands', '荷兰', 'Sovereign state', 'Europe', 'EUR', '31', 'Europe/Amsterdam'),
('NC', 'NCL', '540', 'New Caledonia', '新喀里多尼亚', 'France territory', 'Oceania', 'XPF', '687', 'Pacific/Noumea'),
('NZ', 'NZL', '554', 'New Zealand', '新西兰', 'Sovereign state', 'Oceania', 'NZD', '64', 'Pacific/Auckland'),
('NI', 'NIC', '558', 'Nicaragua', '尼加拉瓜', 'Sovereign state', 'North America', 'NIO', '505', 'America/Managua'),
('NE', 'NER', '562', 'Niger', '尼日尔', 'Sovereign state', 'Africa', 'XOF', '227', 'Africa/Niamey'),
('NG', 'NGA', '566', 'Nigeria', '尼日利亚', 'Sovereign state', 'Africa', 'NGN', '234', 'Africa/Lagos'),
('NU', 'NIU', '570', 'Niue', '纽埃', 'New Zealand territory', 'Oceania', 'NZD', '683', 'Pacific/Niue'),
('NF', 'NFK', '574', 'Norfolk Island', '诺福克岛', 'Australian territory', 'Oceania', 'AUD', '672', 'Pacific/Norfolk'),
('MP', 'MNP', '580', 'Northern Mariana Islands', '北马里亚纳群岛', 'US territory', 'Oceania', 'USD', '1-670', 'Pacific/Saipan'),
('NO', 'NOR', '578', 'Norway', '挪威', 'Sovereign state', 'Europe', 'NOK', '47', 'Europe/Oslo'),
('OM', 'OMN', '512', 'Oman', '阿曼', 'Sovereign state', 'Asia', 'OMR', '968', 'Asia/Muscat'),
('PK', 'PAK', '586', 'Pakistan', '巴基斯坦', 'Sovereign state', 'Asia', 'PKR', '92', 'Asia/Karachi'),
('PW', 'PLW', '585', 'Palau', '帕劳', 'Sovereign state', 'Oceania', 'USD', '680', 'Pacific/Palau'),
('PS', 'PSE', '275', 'Palestine', '巴勒斯坦', 'Observer state', 'Asia', 'ILS', '970', 'Asia/Gaza'),
('PA', 'PAN', '591', 'Panama', '巴拿马', 'Sovereign state', 'North America', 'PAB', '507', 'America/Panama'),
('PG', 'PNG', '598', 'Papua New Guinea', '巴布亚新几内亚', 'Sovereign state', 'Oceania', 'PGK', '675', 'Pacific/Port_Moresby'),
('PY', 'PRY', '600', 'Paraguay', '巴拉圭', 'Sovereign state', 'South America', 'PYG', '595', 'America/Asuncion'),
('PE', 'PER', '604', 'Peru', '秘鲁', 'Sovereign state', 'South America', 'PEN', '51', 'America/Lima'),
('PH', 'PHL', '608', 'Philippines', '菲律宾', 'Sovereign state', 'Asia', 'PHP', '63', 'Asia/Manila'),
('PN', 'PCN', '612', 'Pitcairn', '皮特凯恩', 'UK territory', 'Oceania', 'NZD', '870', 'Pacific/Pitcairn'),
('PL', 'POL', '616', 'Poland', '波兰', 'Sovereign state', 'Europe', 'PLN', '48', 'Europe/Warsaw'),
('PT', 'PRT', '620', 'Portugal', '葡萄牙', 'Sovereign state', 'Europe', 'EUR', '351', 'Europe/Lisbon'),
('PR', 'PRI', '630', 'Puerto Rico', '波多黎各', 'US territory', 'North America', 'USD', '1-787', 'America/Puerto_Rico'),
('QA', 'QAT', '634', 'Qatar', '卡塔尔', 'Sovereign state', 'Asia', 'QAR', '974', 'Asia/Qatar'),
('CG', 'COG', '178', 'Republic of the Congo', '刚果（布）', 'Sovereign state', 'Africa', 'XAF', '242', 'Africa/Brazzaville'),
('MK', 'MKD', '807', 'North Macedonia', '北马其顿', 'Sovereign state', 'Europe', 'MKD', '389', 'Europe/Skopje'),
('RO', 'ROU', '642', 'Romania', '罗马尼亚', 'Sovereign state', 'Europe', 'RON', '40', 'Europe/Bucharest'),
('RU', 'RUS', '643', 'Russian Federation', '俄罗斯', 'Sovereign state', 'Europe', 'RUB', '7', 'Europe/Moscow'),
('RW', 'RWA', '646', 'Rwanda', '卢旺达', 'Sovereign state', 'Africa', 'RWF', '250', 'Africa/Kigali'),
('RE', 'REU', '638', 'Réunion', '留尼汪', 'France territory', 'Africa', 'EUR', '262', 'Indian/Reunion'),
('BL', 'BLM', '652', 'Saint Barthélemy', '圣巴泰勒米', 'France territory', 'North America', 'EUR', '590', 'America/St_Barthelemy'),
('SH', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha', '圣赫勒拿、阿森松和特里斯坦-达库尼亚', 'UK territory', 'Africa', 'SHP', '290', 'Atlantic/St_Helena'),
('KN', 'KNA', '659', 'Saint Kitts and Nevis', '圣基茨和尼维斯', 'Sovereign state', 'North America', 'XCD', '1-869', 'America/St_Kitts'),
('LC', 'LCA', '662', 'Saint Lucia', '圣卢西亚', 'Sovereign state', 'North America', 'XCD', '1-758', 'America/St_Lucia'),
('MF', 'MAF', '663', 'Saint Martin (French part)', '法属圣马丁', 'France territory', 'North America', 'EUR', '590', 'America/St_Martin'),
('PM', 'SPM', '666', 'Saint Pierre and Miquelon', '圣皮埃尔和密克隆', 'France territory', 'North America', 'EUR', '508', 'America/Miquelon'),
('VC', 'VCT', '670', 'Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯', 'Sovereign state', 'North America', 'XCD', '1-784', 'America/St_Vincent'),
('WS', 'WSM', '882', 'Samoa', '萨摩亚', 'Sovereign state', 'Oceania', 'WST', '685', 'Pacific/Apia'),
('SM', 'SMR', '674', 'San Marino', '圣马力诺', 'Sovereign state', 'Europe', 'EUR', '378', 'Europe/San_Marino'),
('ST', 'STP', '678', 'Sao Tome and Principe', '圣多美和普林西比', 'Sovereign state', 'Africa', 'STN', '239', 'Africa/Sao_Tome'),
('SA', 'SAU', '682', 'Saudi Arabia', '沙特阿拉伯', 'Sovereign state', 'Asia', 'SAR', '966', 'Asia/Riyadh'),
('SN', 'SEN', '686', 'Senegal', '塞内加尔', 'Sovereign state', 'Africa', 'XOF', '221', 'Africa/Dakar'),
('RS', 'SRB', '688', 'Serbia', '塞尔维亚', 'Sovereign state', 'Europe', 'RSD', '381', 'Europe/Belgrade'),
('SC', 'SYC', '690', 'Seychelles', '塞舌尔', 'Sovereign state', 'Africa', 'SCR', '248', 'Indian/Mahe'),
('SL', 'SLE', '694', 'Sierra Leone', '塞拉利昂', 'Sovereign state', 'Africa', 'SLL', '232', 'Africa/Freetown'),
('SG', 'SGP', '702', 'Singapore', '新加坡', 'Sovereign state', 'Asia', 'SGD', '65', 'Asia/Singapore'),
('SX', 'SXM', '534', 'Sint Maarten (Dutch part)', '荷属圣马丁', 'Netherlands territory', 'North America', 'ANG', '1-721', 'America/Lower_Prins_Quarter'),
('SK', 'SVK', '703', 'Slovakia', '斯洛伐克', 'Sovereign state', 'Europe', 'EUR', '421', 'Europe/Bratislava'),
('SI', 'SVN', '705', 'Slovenia', '斯洛文尼亚', 'Sovereign state', 'Europe', 'EUR', '386', 'Europe/Ljubljana'),
('SB', 'SLB', '090', 'Solomon Islands', '所罗门群岛', 'Sovereign state', 'Oceania', 'SBD', '677', 'Pacific/Guadalcanal'),
('SO', 'SOM', '706', 'Somalia', '索马里', 'Sovereign state', 'Africa', 'SOS', '252', 'Africa/Mogadishu'),
('ZA', 'ZAF', '710', 'South Africa', '南非', 'Sovereign state', 'Africa', 'ZAR', '27', 'Africa/Johannesburg'),
('GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', '南乔治亚和南桑威奇群岛', 'UK territory', 'Antarctica', 'GBP', '500', 'Atlantic/South_Georgia'),
('SS', 'SSD', '728', 'South Sudan', '南苏丹', 'Sovereign state', 'Africa', 'SSP', '211', 'Africa/Juba'),
('ES', 'ESP', '724', 'Spain', '西班牙', 'Sovereign state', 'Europe', 'EUR', '34', 'Europe/Madrid'),
('LK', 'LKA', '144', 'Sri Lanka', '斯里兰卡', 'Sovereign state', 'Asia', 'LKR', '94', 'Asia/Colombo'),
('SD', 'SDN', '729', 'Sudan', '苏丹', 'Sovereign state', 'Africa', 'SDG', '249', 'Africa/Khartoum'),
('SR', 'SUR', '740', 'Suriname', '苏里南', 'Sovereign state', 'South America', 'SRD', '597', 'America/Paramaribo'),
('SJ', 'SJM', '744', 'Svalbard and Jan Mayen', '斯瓦尔巴和扬马延', 'Norway territory', 'Europe', 'NOK', '47', 'Arctic/Longyearbyen'),
('SE', 'SWE', '752', 'Sweden', '瑞典', 'Sovereign state', 'Europe', 'SEK', '46', 'Europe/Stockholm'),
('CH', 'CHE', '756', 'Switzerland', '瑞士', 'Sovereign state', 'Europe', 'CHF', '41', 'Europe/Zurich'),
('SY', 'SYR', '760', 'Syria', '叙利亚', 'Sovereign state', 'Asia', 'SYP', '963', 'Asia/Damascus'),
('TW', 'TWN', '158', 'Taiwan', '中国台湾', 'Part of China', 'Asia', 'TWD', '886', 'Asia/Taipei'),
('TJ', 'TJK', '762', 'Tajikistan', '塔吉克斯坦', 'Sovereign state', 'Asia', 'TJS', '992', 'Asia/Dushanbe'),
('TZ', 'TZA', '834', 'Tanzania', '坦桑尼亚', 'Sovereign state', 'Africa', 'TZS', '255', 'Africa/Dar_es_Salaam'),
('TH', 'THA', '764', 'Thailand', '泰国', 'Sovereign state', 'Asia', 'THB', '66', 'Asia/Bangkok'),
('TL', 'TLS', '626', 'Timor-Leste', '东帝汶', 'Sovereign state', 'Asia', 'USD', '670', 'Asia/Dili'),
('TG', 'TGO', '768', 'Togo', '多哥', 'Sovereign state', 'Africa', 'XOF', '228', 'Africa/Lome'),
('TK', 'TKL', '772', 'Tokelau', '托克劳', 'New Zealand territory', 'Oceania', 'NZD', '690', 'Pacific/Fakaofo'),
('TO', 'TON', '776', 'Tonga', '汤加', 'Sovereign state', 'Oceania', 'TOP', '676', 'Pacific/Tongatapu'),
('TT', 'TTO', '780', 'Trinidad and Tobago', '特立尼达和多巴哥', 'Sovereign state', 'North America', 'TTD', '1-868', 'America/Port_of_Spain'),
('TN', 'TUN', '788', 'Tunisia', '突尼斯', 'Sovereign state', 'Africa', 'TND', '216', 'Africa/Tunis'),
('TR', 'TUR', '792', 'Turkey', '土耳其', 'Sovereign state', 'Asia', 'TRY', '90', 'Europe/Istanbul'),
('TM', 'TKM', '795', 'Turkmenistan', '土库曼斯坦', 'Sovereign state', 'Asia', 'TMT', '993', 'Asia/Ashgabat'),
('TC', 'TCA', '796', 'Turks and Caicos Islands', '特克斯和凯科斯群岛', 'UK territory', 'North America', 'USD', '1-649', 'America/Grand_Turk'),
('TV', 'TUV', '798', 'Tuvalu', '图瓦卢', 'Sovereign state', 'Oceania', 'AUD', '688', 'Pacific/Funafuti'),
('UG', 'UGA', '800', 'Uganda', '乌干达', 'Sovereign state', 'Africa', 'UGX', '256', 'Africa/Kampala'),
('UA', 'UKR', '804', 'Ukraine', '乌克兰', 'Sovereign state', 'Europe', 'UAH', '380', 'Europe/Kiev'),
('AE', 'ARE', '784', 'United Arab Emirates', '阿联酋', 'Sovereign state', 'Asia', 'AED', '971', 'Asia/Dubai'),
('GB', 'GBR', '826', 'United Kingdom', '英国', 'Sovereign state', 'Europe', 'GBP', '44', 'Europe/London'),
('US', 'USA', '840', 'United States of America', '美国', 'Sovereign state', 'North America', 'USD', '1', 'America/New_York'),
('UM', 'UMI', '581', 'United States Minor Outlying Islands', '美国本土外小岛屿', 'US territory', 'Oceania', 'USD', '1', 'Pacific/Midway'),
('UY', 'URY', '858', 'Uruguay', '乌拉圭', 'Sovereign state', 'South America', 'UYU', '598', 'America/Montevideo'),
('UZ', 'UZB', '860', 'Uzbekistan', '乌兹别克斯坦', 'Sovereign state', 'Asia', 'UZS', '998', 'Asia/Tashkent'),
('VU', 'VUT', '548', 'Vanuatu', '瓦努阿图', 'Sovereign state', 'Oceania', 'VUV', '678', 'Pacific/Efate'),
('VE', 'VEN', '862', 'Venezuela', '委内瑞拉', 'Sovereign state', 'South America', 'VES', '58', 'America/Caracas'),
('VN', 'VNM', '704', 'Viet Nam', '越南', 'Sovereign state', 'Asia', 'VND', '84', 'Asia/Ho_Chi_Minh'),
('VI', 'VIR', '850', 'U.S. Virgin Islands', '美属维尔京群岛', 'US territory', 'North America', 'USD', '1-340', 'America/St_Thomas'),
('WF', 'WLF', '876', 'Wallis and Futuna', '瓦利斯和富图纳', 'France territory', 'Oceania', 'XPF', '681', 'Pacific/Wallis'),
('EH', 'ESH', '732', 'Western Sahara', '西撒哈拉', 'Disputed', 'Africa', 'MAD', '212', 'Africa/El_Aaiun'),
('YE', 'YEM', '887', 'Yemen', '也门', 'Sovereign state', 'Asia', 'YER', '967', 'Asia/Aden'),
('ZM', 'ZMB', '894', 'Zambia', '赞比亚', 'Sovereign state', 'Africa', 'ZMW', '260', 'Africa/Lusaka'),
('ZW', 'ZWE', '716', 'Zimbabwe', '津巴布韦', 'Sovereign state', 'Africa', 'ZWL', '263', 'Africa/Harare'),
('AX', 'ALA', '248', 'Åland Islands', '奥兰群岛', 'Finland territory', 'Europe', 'EUR', '358', 'Europe/Mariehamn'),
('BV', 'BVT', '074', 'Bouvet Island', '布韦岛', 'Norway territory', 'Antarctica', 'NOK', '47', 'Europe/Oslo'),
('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba', '博内尔、圣尤斯特歇斯和萨巴', 'Netherlands territory', 'North America', 'USD', '599', 'America/Kralendijk'),
('XK', 'UNK', '999', 'Kosovo', '科索沃', 'Disputed', 'Europe', 'EUR', '383', 'Europe/Belgrade');